name: memcache_sample
version: 0.2.0
description: A sample application showing the use of memcache with managed VMs
dependencies:
  appengine: '>=0.2.1 <0.3.0'
  mustache: '>=0.1.8 <0.2.0'
transformers:
- $dart2js:
    $exclude: bin/**.dart
