name: dart_client_sample
version: 0.1.0
description: A sample application serving a Dart web client.
dependencies:
  appengine:
    git:
      url: https://github.com/dart-lang/appengine
      ref: v0.1
  browser: any
