name: simple_request_response
description: A sample application only serving client requests.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  appengine: '^0.3.0'
transformers:
- $dart2js:
    $exclude: bin/**.dart
