name: simple_request_response
version: 0.2.0
description: A sample application only serving client requests.
dependencies:
  appengine: '>=0.2.1 <0.3.0'
transformers:
- $dart2js:
    $exclude: bin/**.dart
