name: simple_request_response_sample
version: 0.1.0
description: A sample application only serving client requests.
dependencies:
  appengine:
    git:
      url: https://github.com/dart-lang/appengine
      ref: v0.1
