name: cloud_datastore_sample
version: 0.1.0
description: A sample application showing the use of Cloud Datastore
dependencies:
  appengine: any
  cloud_datastore: any
  mustache: '>=0.1.8 <0.2.0'
dependency_overrides:
  appengine:
    path: ../../appengine
  cloud_datastore:
    path: ../../cloud_datastore
  memcache:
    path: ../../memcache
