name: memcache_sample
version: 0.1.0
description: A sample application showing the use of memcache with managed VMs
dependencies:
  appengine:
    git:
      url: https://github.com/dart-lang/appengine
      ref: v0.1
  memcache:
    git:
      url: https://github.com/dart-lang/memcache
      ref: v0.1
  mustache: '>=0.1.8 <0.2.0'
